version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewKrttProject
  gitServerName: krt
  gitUrl: https://github.com/Kruthika-K-IBM
  gitUsername: Kruthika-K-IBM
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: WmIBMPowerAdapter
  version: 10.11.0.0.77
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections:sas
  packages:
  - name: NewKrttProject
    version: "1.0"
  - name: WmIBMPowerAdapter
    version: 10.11.0.0.77
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: NewKrttProject
    version: "1.0"
  - name: WmIBMPowerAdapter
    version: 10.11.0.0.77
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.newkrtt.integrations:NewFL
  packages:
  - name: NewKrttProject
    version: "1.0"
  - name: WmIBMPowerAdapter
    version: 10.11.0.0.77
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.socketProperties
  : ""
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.isSecureConnection
  : "false"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.systemName
  : sas
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : sas
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.password
  : "{AES}Bwp8P3PjMHFuiv538jP+vQ=="
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.proxyEndpoint
  : ""
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : ORACLE
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}aLZqGGNedYRdf0xY47LtDQ=="
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "false"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : ""
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : asas
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionManagerSettings.poolable
  : "false"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.userId
  : asa
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.proxyEncryptionMode
  : CLIENT_TO_SERVER
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionEnabled
  : "false"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.useDefaultUser
  : "false"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.serviceType
  : COMMAND
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.otherProperties
  : ""
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.currentLibrary
  : sas
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : ""
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "1521"
  ? artConnection.NewKrttProject.project.newkrtt.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.NewKrttProject.project.newkrtt.WmIBMPowerAdapter.com_wm_adapter_ibmp_WmIBMPowerAdapter.connections.sas.connectionSettings.useProxyServer
  : "false"
